### ISSUE TITLE
[BUG]readme cookiecutter install command is outdated

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#1]
### Description
running this: 
`cookiecutter gh:Microsoft/AMLDistCC`
causes this error:
`"The repository https://github.com/Microsoft/AMLDistCC.git could not be found, have you made a typo?"`

update readme to `cookiecutter gh:Microsoft/DistributedDeepLearning`

### In which platform does it happen?
ubuntu 18

### Other Comments

**Comment by msalvaris** [comment]
Fixes in #10
