### ISSUE TITLE
[QUESTION] Native docker experience vs tmux

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#11]
### Description
i personally like the tmux experience, but should we impose this as the default? people not familiar with tmux will surely find navigating it confusing. 

An alternate experience, which _may_ seem more neutral is one where `make run` doesn't start tmux by default. Users would have to use another command like `make run_with_tmux` or something if they wanted to use tmux as their session manager. Not really sure.. probably worth getting more opinions on this.

### Other Comments

**Comment by msalvaris** [comment]
Good point. We should definitely look for feedback on this
