### ISSUE TITLE
[QUESTION] ambiguity of setup parameters

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#2]
### Description
- Not sure if i need the cookiecutter param 'data' if i do not select 'imagenet' for the _type_ since the description says that it is the location to store imagenet
- _type_ 'image_name' feels ambiguous. users don't know ahead of time that the are using a docker image as a control plane. maybe specify in the cookiecutter prompt that it is a docker image? or rename to `docker_image_name`
- cookiecutter prompts for datastore name as 'account name', which is ambiguous (account of what?) and not reflected in the readme
- same issue for prompting 'account key', naming is ambiguous. Also, shouldn't this be generated? instead of prompting a user for it. (also not reflected in the readme)
- perhaps rename 'container_name' -> 'storage_container_name' (since people may mix up the term container)

### Other Comments

**Comment by msalvaris** [comment]
Nice catches, will address
