### ISSUE TITLE
[QUESTION] Selected type == 'template', but see folders for 'benchmark', 'imagenet', and 'experiment'

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#3]
### Description
During the cookiecutter setup, i selected type == 'template', however, the project that got created has the following three folders:
- 'Tensorflow_experiment'
- 'Tensorflow_benchmark'
- 'Tensorflow_imagenet'

Since i only selected 'template', should expect to _only_ see one folder - 'Tensorflow_template' or something like that?

### Other Comments

**Comment by msalvaris** [comment]
Yea, that is a bug. Template==Experiment though. As generating a folder called template is a bit misleading after generation. The naming isn't perfect, do you have any suggestions?

**Comment by jiata** [comment]
yeah good point. i do think 'template' is a better name. but yes, not ideal.
