### ISSUE TITLE
[FEATURE] templatize environment name in environment_gpu/cpu.ymls

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#4]
### Description
Users may want to test locally within the conda env before running is via aml (at least i do), so i build the environment locally first. However, if i build it as is, my environment name will be 'project_environment', when it should probably be one of the parameters passed into cookiecutter during the setup.

### Expected behavior with the suggested feature
running `conda env create -f environment_gpu.yml` should create an environment named something more appropriate than `project_environment`

### Other Comments

**Comment by msalvaris** [comment]
Do you think it should be the experiment name or just something like distributed training env?

**Comment by jiata** [comment]
could make 'project' a prompt in cookiecutter, and use `<project>_env`.

**Comment by msalvaris** [comment]
That sounds reasonable. Will add that
