### ISSUE TITLE
[BUG] environment_<gpu/cpu>.yml reference path is incorrect in tensorflow_experiments.py

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#6]
### Description
inside the inv file, the reference to 'dependencies_file' should be:
`dependencies_file="TensorFlow_experiment/environment_gpu.yml"` instead of `dependencies_file="Tensorflow/environment_gpu.yml"`

This applies for all four template functions inside the tensorflow_experiments.py inv file.

### Other Comments

**Comment by msalvaris** [comment]
Fixed in #12
