### ISSUE TITLE
[FEATURE] Add example to implement from for guidance

### ISSUE THREAD

**Issue by jiata** [microsoft/DistributedDeepLearning#9]
### Description
Provide some guidance on what people could use when implementing the template, and what to look for in the AML portal.

### Expected behavior with the suggested feature
A concrete example will give users something to run. For example, pointing them to something like this script might be useful: https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist_estimator.py

### Other Comments

**Comment by msalvaris** [comment]
Good idea. Good you create a PR for this?
